import type { SupplierQuote } from "@/types/rfq";

export const mockQuotes: SupplierQuote[] = [
  {
    supplierName: "Atlas Industrial",
    quoteNumber: "AT-1042",
    quoteDate: "2026-05-12",
    currency: "USD",
    paymentTerms: "Net 30",
    overallLeadTime: "10 days",
    lineItems: [
      {
        id: "atlas-1",
        itemName: "Steel Pipe 2 inch",
        description: "Schedule 40",
        quantity: 20,
        unitPrice: 8.4,
        totalPrice: 168,
        unitOfMeasure: "ea",
        leadTime: "10 days",
        minimumOrderQuantity: 10,
        notes: null,
        confidenceScore: 0.97,
      },
      {
        id: "atlas-2",
        itemName: "Industrial Valve 1 inch",
        description: "Brass",
        quantity: 8,
        unitPrice: 22,
        totalPrice: 176,
        unitOfMeasure: "ea",
        leadTime: "14 days",
        minimumOrderQuantity: null,
        notes: "Freight excluded",
        confidenceScore: 0.74,
      },
    ],
  },
  {
    supplierName: "Beacon Supply",
    quoteNumber: "BC-882",
    quoteDate: "2026-05-13",
    currency: "USD",
    paymentTerms: "Net 15",
    overallLeadTime: "7 days",
    lineItems: [
      {
        id: "beacon-1",
        itemName: "2-inch steel pipe",
        description: "Schedule 40",
        quantity: 20,
        unitPrice: 7.95,
        totalPrice: 159,
        unitOfMeasure: "ea",
        leadTime: "7 days",
        minimumOrderQuantity: 10,
        notes: null,
        confidenceScore: 0.98,
      },
      {
        id: "beacon-2",
        itemName: "Pipe Clamp",
        description: "Galvanized",
        quantity: 20,
        unitPrice: 2.5,
        totalPrice: 50,
        unitOfMeasure: "ea",
        leadTime: "5 days",
        minimumOrderQuantity: null,
        notes: null,
        confidenceScore: 0.94,
      },
    ],
  },
];
